name: Make and Run Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
           
  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: |
        cd c++/
        make main
    - name: run
      run: |
        cd c++/
        ./main file.tnl
